# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Superid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SuperidToLoanLiability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantee', models.IntegerField(default=0)),
                ('maturity_date', models.DateField(null=True)),
                ('ledger', models.CharField(max_length=255)),
                ('closed', models.BooleanField(default=False)),
                ('liability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdradmin.Liability')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdradmin.Loan')),
                ('superid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdradmin.Superid')),
            ],
        ),
    ]
