# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lishortdescription', models.CharField(max_length=255)),
                ('Lidescription', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loshortdescription', models.CharField(max_length=255)),
                ('LoDescription', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Superid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='Losuperid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdradmin.Superid'),
        ),
        migrations.AddField(
            model_name='liability',
            name='Lisuperid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdradmin.Superid'),
        ),
    ]
