# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superidtoloanliability',
            name='country_of_utilization',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
