# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liability',
            old_name='Lidescription',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='liability',
            old_name='Lishortdescription',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='LoDescription',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='Loshortdescription',
            new_name='short_description',
        ),
        migrations.RemoveField(
            model_name='liability',
            name='Lisuperid',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='Losuperid',
        ),
        migrations.AddField(
            model_name='superid',
            name='liability',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cdradmin.Liability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superid',
            name='loan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cdradmin.Loan'),
            preserve_default=False,
        ),
    ]
