# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0002_superidtoloanliability_country_of_utilization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='superidtoloanliability',
            name='country_of_utilization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdradmin.Country'),
        ),
    ]
