# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0002_auto_20170821_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperidToLoanLiability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdradmin.Liability')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdradmin.Loan')),
            ],
        ),
        migrations.RemoveField(
            model_name='superid',
            name='liability',
        ),
        migrations.RemoveField(
            model_name='superid',
            name='loan',
        ),
        migrations.AddField(
            model_name='superidtoloanliability',
            name='superid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdradmin.Superid'),
        ),
    ]
