# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0003_auto_20170821_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='superidtoloanliability',
            name='country_of_utilzation',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superidtoloanliability',
            name='ledger',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superidtoloanliability',
            name='maturity_date',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
