# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0004_auto_20171023_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superidtoloanliability',
            old_name='country_of_utilzation',
            new_name='country_of_utilization',
        ),
    ]
