# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0005_auto_20171023_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superidtoloanliability',
            name='maturity_date',
            field=models.DateField(),
        ),
    ]
