# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0005_auto_20180117_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superidtoloanliability',
            name='ledger',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
