# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0006_delete_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
