# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0008_auto_20180108_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superidtoloanliability',
            name='country_of_utilization',
        ),
    ]
