# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0008_auto_20180117_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superidtoloanliability',
            name='country_of_utilization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdradmin.Country'),
        ),
        migrations.AlterField(
            model_name='superidtoloanliability',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdradmin.Currency'),
        ),
    ]
