# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0009_auto_20180117_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superidtoloanliability',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
