# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0012_auto_20180108_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superidtoloanliability',
            name='country_of_utilization',
            field=models.CharField(max_length=255),
        ),
    ]
