# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-01 09:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0012_auto_20180119_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='superidtoloanliability',
            name='subledger',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
