# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0014_auto_20180201_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='superidtoloanliability',
            name='loan_amount',
            field=models.IntegerField(default=0),
        ),
    ]
