# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0015_superidtoloanliability_loan_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superidtoloanliability',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_liability', to='cdradmin.Currency'),
        ),
        migrations.AlterField(
            model_name='superidtoloanliability',
            name='currency_guarantee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_guarantee', to='cdradmin.Currency'),
        ),
        migrations.DeleteModel(
            name='CurrencyGuarantee',
        ),
    ]
