# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0016_auto_20180212_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superidtoloanliability',
            old_name='currency',
            new_name='currency_liability',
        ),
        migrations.RenameField(
            model_name='superidtoloanliability',
            old_name='guarantee',
            new_name='guarantee_amount',
        ),
        migrations.RenameField(
            model_name='superidtoloanliability',
            old_name='liability',
            new_name='liability_type',
        ),
        migrations.RenameField(
            model_name='superidtoloanliability',
            old_name='loan',
            new_name='loan_type',
        ),
        migrations.RemoveField(
            model_name='superidtoloanliability',
            name='currency_guarantee',
        ),
        migrations.AddField(
            model_name='superidtoloanliability',
            name='guarantee_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_currency', to='cdradmin.Currency'),
        ),
    ]
