# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0018_auto_20180212_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='partner_type',
        ),
    ]
