# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0019_auto_20180116_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={},
        ),
    ]
