# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0019_remove_entity_partner_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityToPartnerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdradmin.Entity')),
                ('partner_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdradmin.Partner_type')),
            ],
        ),
    ]
