# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0020_entitytopartnertype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superidtoloanliability',
            options={'ordering': ['superid__superid', 'ledger__ledger', 'subledger', 'currency_liability']},
        ),
        migrations.AddField(
            model_name='superidtoloanliability',
            name='guarantee_for',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdradmin.SuperidToLoanLiability'),
        ),
        migrations.AlterUniqueTogether(
            name='superidtoloanliability',
            unique_together=set([('superid', 'ledger', 'subledger', 'currency_liability')]),
        ),
    ]
