# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 09:49
#
# After adding guarantee_for field,
# need to automatically split out new entries for the guarantees
#
# Skeleton copied from django RunPython documentation here
# https://docs.djangoproject.com/en/2.0/ref/migration-operations/#runpython
from __future__ import unicode_literals

from django.db import migrations

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    SuperidToLoanLiability = apps.get_model("cdradmin", "SuperidToLoanLiability")
    Liability = apps.get_model("cdradmin", "Liability")
    db_alias = schema_editor.connection.alias
    to_create = []
    for stll in SuperidToLoanLiability.objects.exclude(guarantee_amount=0):
      try:
        guarantee_type = Liability.objects.get(short_description=stll.guarantee_type)
      except:
        print("liability_type %s not found?"%stll.guarantee_type)
        print(Liability.objects.all().values_list('short_description', flat=True))
        # guarantee_type = Liability.objects.create(short_description=stll.guarantee_type, long_description=stll.guarantee_type)
        raise

      to_create.append(SuperidToLoanLiability(
        superid = stll.superid,
        loan_type = stll.loan_type, # e.g. Z3
        loan_amount = stll.guarantee_amount,
        liability_type = guarantee_type, # e.g. ACB / TCB
        guarantee_amount = 0,
        guarantee_type = '',
        maturity_date = stll.maturity_date,
        ledger = stll.ledger,
        subledger = 7+stll.subledger,
        country_of_utilization = stll.country_of_utilization,
        currency_liability = stll.guarantee_currency,
        guarantee_currency = None,
        closed = stll.closed,
        guarantee_for = stll
      ))

    SuperidToLoanLiability.objects.using(db_alias).bulk_create(to_create)

def reverse_func(apps, schema_editor):
    # forwards_func() creates SuperidToLoanLiability instances,
    # so reverse_func() should delete them.
    SuperidToLoanLiability = apps.get_model("cdradmin", "SuperidToLoanLiability")
    db_alias = schema_editor.connection.alias
    SuperidToLoanLiability.objects.using(db_alias).filter(guarantee_for__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0021_auto_20180309_0949'),
    ]

    operations = [
      migrations.RunPython(forwards_func, reverse_func),
    ]
