# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0022_superidtoloanliability_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superidtoloanliability',
            name='currency',
            field=models.CharField(max_length=255),
        ),
    ]
