# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0023_auto_20180116_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superidtoloanliability',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdradmin.Currency'),
        ),
    ]
