# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0024_auto_20180312_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superidtoloanliability',
            name='guarantee_amount',
        ),
        migrations.RemoveField(
            model_name='superidtoloanliability',
            name='guarantee_currency',
        ),
        migrations.RemoveField(
            model_name='superidtoloanliability',
            name='guarantee_type',
        ),
    ]
