# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0024_auto_20180116_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
