# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0025_auto_20180312_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superidtoloanliability',
            name='currency_liability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_liability', to='cdradmin.Currency'),
        ),
    ]
