# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0026_auto_20180117_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='description',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
