# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0027_superidtoloanliability_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='superid',
            name='account',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='superid',
            unique_together=set([('superid', 'account')]),
        ),
    ]
