# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0028_auto_20180312_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superid',
            options={'ordering': ('superid', 'account')},
        ),
    ]
