# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0029_auto_20180312_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superidtoloanliability',
            name='ledger',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdradmin.Ledger', verbose_name='Ledger (skip for TSR/TBI)'),
        ),
        migrations.AlterField(
            model_name='superidtoloanliability',
            name='loan_amount',
            field=models.IntegerField(default=0, verbose_name="Loan amount (use 0 for 'From MF')"),
        ),
    ]
