# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdradmin', '0031_auto_20180312_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='cdr_code',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
